name: "Builder"

jobs:
  build:
    name: build
    runs-on: ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Unity
        uses: kuler90/setup-unity@v1
        with:
          unity-modules: android
